Repository SalehAhmed19/Mehraf-All-IT-Solutions, pull requests merged in 2022-10, with the labels that each got.

#4 Home Page Added
  src/Pages/Home/Banner/Banner.jsx
  src/index.css
  tailwind.config.js
Labels: enhancement

#6 routes added and home page designed
  src/App.css
  src/App.js
  src/Assets/images/banner.png
  src/Pages/Home/Banner/Banner.css
  src/Pages/Home/Banner/Banner.jsx
  src/Pages/Home/Featured/Freatured.jsx
  src/Pages/Home/Home/Home.jsx
  src/Shared/Footer/Footer.jsx
  src/Shared/Navbar/Navbar.jsx
  src/index.css
Labels: enhancement

#7 simple channges
  src/Pages/Home/Banner/Banner.jsx
Labels: enhancement

#8 banner changes
  src/Pages/Home/Banner/Banner.jsx
Labels: enhancement

#9 banner changes
  src/Pages/Home/Banner/Banner.jsx
Labels: enhancement

#12 Ra/login page#2
  package-lock.json
  package.json
  src/App.js
  src/Pages/Home/Login/Login.jsx
  src/Shared/Navbar/Navbar.jsx
Labels: enhancement

#14 featured survices added
  package-lock.json
  src/Assets/images/banner.jpeg
  src/Pages/Home/Banner/Banner.jsx
  src/Pages/Home/Discount/Discount.jsx
  src/Pages/Home/Featured/Freatured.jsx
  src/Shared/Footer/Footer.jsx
Labels: enhancement

#15 some changes on card
  src/Assets/images/digital-marketing.jpeg
  src/Assets/images/graphics-design.jpeg
  src/Assets/images/web-design.jpeg
  src/Assets/images/web-development.jpeg
  src/Pages/Home/Featured/Freatured.jsx
Labels: enhancement

#16 some changes on card
  src/App.css
  src/Pages/Home/Banner/Banner.css
  src/Pages/Home/Banner/Banner.jsx
  src/Pages/Home/Featured/Freatured.jsx
Labels: enhancement

#17 some changes on card
  src/Pages/Home/Featured/Freatured.jsx
Labels: enhancement

#18 some style changed
  src/Assets/images/logo.png
  src/Assets/images/mehraf.png
  src/Pages/Home/Banner/Banner.jsx
  src/Pages/Home/Featured/Freatured.jsx
  src/Shared/Footer/Footer.jsx
  src/Shared/Navbar/Navbar.jsx
Labels: enhancement

#19 why us section added
  src/Pages/Home/Home/Home.jsx
  src/Pages/Home/WhyUs/WhyUs.css
  src/Pages/Home/WhyUs/WhyUs.jsx
Labels: enhancement

#21 card changed
  package-lock.json
  package.json
  src/Pages/Home/WhyUs/WhyUs.jsx
  src/Shared/Navbar/Navbar.jsx
Labels: enhancement

#22 Sam/home page#3
  .firebase/hosting.YnVpbGQ.cache
  .firebaserc
  firebase.json
  src/Pages/Home/Featured/Freatured.jsx
Labels: enhancement

#25 Sam/home page#3
  .firebase/hosting.YnVpbGQ.cache
  package-lock.json
  package.json
  src/App.js
  src/Shared/Navbar/Navbar.jsx
Labels: enhancement

#26 Develop
  .firebase/hosting.YnVpbGQ.cache
  .firebaserc
  firebase.json
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/Assets/images/banner.jpeg
  src/Assets/images/digital-marketing.jpeg
  src/Assets/images/graphics-design.jpeg
  src/Assets/images/logo.png
  src/Assets/images/mehraf.png
  src/Assets/images/web-design.jpeg
  src/Assets/images/web-development.jpeg
  src/Pages/Home/Banner/Banner.css
  src/Pages/Home/Banner/Banner.jsx
  src/Pages/Home/Discount/Discount.jsx
  src/Pages/Home/Featured/Freatured.jsx
  src/Pages/Home/Home/Home.jsx
  src/Pages/Home/Login/Login.jsx
  src/Pages/Home/WhyUs/WhyUs.css
  src/Pages/Home/WhyUs/WhyUs.jsx
  src/Shared/Footer/Footer.jsx
  src/Shared/Navbar/Navbar.jsx
Labels: enhancement

#29 Ra/login page#2
  package-lock.json
  package.json
  src/App.js
  src/Pages/Home/Login/Login.jsx
  src/Pages/Home/Register/Register.js
  src/firebase.init.js
Labels: enhancement

#31 Sam/implemented whats app#23
  package-lock.json
  src/App.js
Labels: enhancement

#32 google user
  src/Pages/Home/Login/Login.jsx
  src/Pages/Home/Register/Register.js
  src/Shared/Loading/Loading.css
  src/Shared/Loading/Loading.jsx
Labels: enhancement

#35 redesigned the navbar and implement search box
  src/Pages/Home/AppDrawer/AppDrawer.jsx
  src/Shared/Navbar/Navbar.jsx
  src/Shared/Navbar/SearchBar.jsx
Labels: enhancement

#36 featured card style changed
  src/Pages/Home/Featured/Freatured.jsx
Labels: enhancement

#37 banner style changed
  src/App.css
  src/Assets/images/banner.png
  src/Pages/Home/Banner/Banner.jsx
  src/Pages/Home/Featured/Freatured.jsx
  src/Pages/Home/WhyUs/WhyUs.jsx
Labels: enhancement

#38 Sam/home page#3
  .firebase/hosting.YnVpbGQ.cache
  src/App.css
  src/Pages/Home/Home/Home.jsx
  src/Pages/Home/Services/Services.jsx
Labels: enhancement

#39 about section added
  package-lock.json
  src/App.css
  src/Assets/images/woman.jpg
  src/Pages/Home/About/About.jsx
  src/Pages/Home/Home/Home.jsx
  src/Pages/Home/Pricing/Pricing.jsx
Labels: enhancement

#40 Ra/login page#2
  src/Pages/Home/Login/Login.jsx
  src/Pages/Home/Register/Register.js
  src/Shared/Navbar/Navbar.jsx
Labels: enhancement

#41 Sam/home page#3
  .firebase/hosting.YnVpbGQ.cache
  src/Assets/images/B&W.png
  src/Assets/images/banner.png
  src/Assets/images/footer.png
  src/Assets/images/service-bg.jpeg
  src/Assets/images/service-bg.png
  src/Assets/images/service-bg.webp
  src/Pages/Home/About/About.jsx
  src/Pages/Home/Services/Services.jsx
  src/Shared/Footer/Footer.jsx
Labels: enhancement

#43 some changed
  src/Pages/Home/Services/Services.jsx
Labels: enhancement

#44 Sam/home page#3
  .firebase/hosting.YnVpbGQ.cache
  src/App.js
  src/Pages/Home/About/About.jsx
  src/Pages/Home/Services/DigitalMarketing/DigitalMarketing.jsx
  src/Pages/Home/Services/GraphicDesign/GraphicDesign.jsx
  src/Pages/Home/Services/Services.jsx
  src/Pages/Home/Services/VideoAnimation/VideoAnimation.jsx
  src/Pages/Home/Services/WebDevelopment/WebDevelopment.jsx
  src/Shared/Navbar/Navbar.jsx
Labels: enhancement

#45 Ra/login page#2
  src/Pages/Home/Login/Login.jsx
  src/Pages/Home/Register/Register.js
  src/Shared/Navbar/Navbar.jsx
Labels: enhancement

#46 banner heading changed
  .firebase/hosting.YnVpbGQ.cache
  src/Pages/Home/Banner/Banner.jsx
Labels: enhancement

#47 validate the form in register page
  src/Pages/Home/Register/Register.js
Labels: enhancement

#49 contact page added
  src/Assets/images/bg.png
  src/Assets/images/contact.png
  src/Assets/images/contact2-01.png
  src/Assets/images/contact3.png
  src/Pages/Contact/Contact.jsx
  src/Pages/Home/About/About.jsx
  src/Pages/Home/Home/Home.jsx
  src/Shared/Navbar/Navbar.jsx
Labels: enhancement

#50 contact via email implemented
  package-lock.json
  package.json
  src/Pages/Contact/Contact.jsx
Labels: enhancement

#52 some changed
  .firebase/hosting.YnVpbGQ.cache
Labels: enhancement

#53 some changed
  src/Pages/Contact/Contact.jsx
Labels: duplicate, enhancement

#54 Sam/home page#3
  .firebase/hosting.YnVpbGQ.cache
  src/Pages/Home/Banner/Banner.jsx
Labels: enhancement

#55 some changed
  .firebase/hosting.YnVpbGQ.cache
  src/Pages/Home/Banner/Banner.jsx
Labels: enhancement

#56 some changes in banner
  .firebase/hosting.YnVpbGQ.cache
  package-lock.json
  package.json
  src/Assets/images/bg.png
  src/Assets/images/contact3.png
  src/Pages/Home/About/About.jsx
  src/Pages/Home/Banner/Banner.jsx
Labels: enhancement

#57 whatsapp number updated
  src/App.js
Labels: enhancement

#58 contact form field required
  src/Pages/Contact/Contact.jsx
Labels: enhancement

#59 react-toastify implemented
  package-lock.json
  package.json
  src/App.js
  src/Pages/Contact/Contact.jsx
Labels: enhancement

#61 Sam/home page#3
  src/Pages/Contact/Contact.jsx
  src/Pages/Home/About/About.jsx
  src/Pages/Home/Banner/Banner.jsx
Labels: enhancement

#63 footer style changed
  src/Pages/Home/About/About.jsx
  src/Pages/Home/Services/Services.jsx
  src/Shared/Footer/Footer.jsx
Labels: enhancement

#64 footer style changed
  .firebase/hosting.YnVpbGQ.cache
  src/App.js
  src/Shared/Footer/Footer.jsx
Labels: enhancement

#65 footer style changed
  .firebase/hosting.YnVpbGQ.cache
  src/Shared/Footer/Footer.jsx
Labels: enhancement

#66 services section redesigned
  .firebase/hosting.YnVpbGQ.cache
  package-lock.json
  package.json
  src/Assets/images/digital-marketing.jpeg
  src/Assets/images/digitalmarketing.png
  src/Assets/images/graphicdesign.png
  src/Assets/images/graphics-design.jpeg
  src/Assets/images/videoedit.png
  src/Assets/images/web-design.jpeg
  src/Assets/images/web-development.jpeg
  src/Assets/images/webdevelopment.png
  src/Pages/Contact/Contact.jsx
  src/Pages/Home/Home/Home.jsx
  src/Pages/Home/Services/Services.jsx
Labels: enhancement

#67 about ection redesigned
  .firebase/hosting.YnVpbGQ.cache
  src/Assets/images/it.png
  src/Pages/Home/About/About.jsx
Labels: enhancement

#69 Sam/home page#3
  .firebase/hosting.YnVpbGQ.cache
  src/App.js
  src/Pages/Home/Discount/Discount.css
  src/Pages/Home/Discount/Discount.jsx
  src/Shared/Footer/Footer.jsx
  src/Shared/Navbar/Navbar.jsx
Labels: enhancement

#70 conflict solved
  src/App.js
Labels: enhancement

#71 faq added
  src/Pages/Home/Faq/Faq.jsx
  src/Pages/Home/Home/Home.jsx
Labels: enhancement

#72 FAQ font fix
  src/Pages/Home/Faq/Faq.jsx
Labels: enhancement

#73 font changed
  .firebase/hosting.YnVpbGQ.cache
  src/App.css
  src/Pages/Home/About/About.jsx
  src/Pages/Home/Discount/Discount.css
Labels: enhancement

#74 banner text changed
  package-lock.json
  package.json
  src/Pages/Home/Banner/Banner.jsx
Labels: enhancement

#75 Sam/home page#3
  .firebase/hosting.YnVpbGQ.cache
  package-lock.json
  package.json
  src/Shared/Footer/Footer.jsx
Labels: enhancement

#76 Sam/home page#3
  .firebase/hosting.YnVpbGQ.cache
  public/favicon.ico
  public/index.html
  src/Assets/images/bg.png
  src/Pages/Home/About/About.jsx
  src/Pages/Home/Banner/Banner.jsx
  src/Pages/Home/Services/Services.jsx
  src/Shared/Footer/Footer.jsx
Labels: enhancement

#77 cursor styled
  .firebase/hosting.YnVpbGQ.cache
  package-lock.json
  package.json
  src/App.js
Labels: enhancement

#78 contact page style changed
  src/Pages/Contact/Contact.jsx
Labels: enhancement

#79 deployment updated
  .firebase/hosting.YnVpbGQ.cache
  package-lock.json
  package.json
  public/favicon.ico
  src/App.js
  src/Assets/images/bg.png
  src/Assets/images/contact3.png
  src/Assets/images/it.png
  src/Assets/images/videoEditing.png
  src/Pages/Contact/Contact.jsx
  src/Pages/Home/About/About.jsx
  src/Pages/Home/Banner/Banner.jsx
  src/Pages/Home/Faq/Faq.jsx
  src/Pages/Home/Services/Services.jsx
  src/Shared/Footer/Footer.jsx
Labels: enhancement

#80 some animation added
  .firebase/hosting.YnVpbGQ.cache
Labels: enhancement

#81 some animation added
  .firebase/hosting.YnVpbGQ.cache
Labels: enhancement

#82 contact page image switching in responsive
  src/Assets/images/contact.png
  src/Assets/images/contact2.png
  src/Pages/Contact/Contact.jsx
Labels: enhancement

#83 scroll behavior fixed
  src/App.js
  src/Pages/Contact/Contact.jsx
  src/Pages/Home/Faq/Faq.jsx
  src/Shared/Navbar/Navbar.jsx
  src/index.css
Labels: enhancement

#84 service effect changes
  .firebase/hosting.YnVpbGQ.cache
  src/Pages/Home/Services/Services.jsx
Labels: enhancement

#85 Ra/login page#2
  package-lock.json
  src/Pages/Home/Services/Services.jsx
  src/Pages/MobileAuth/MobileAuth.jsx
Labels: enhancement

#86 some issues fix
  src/Pages/Home/Services/Services.jsx
Labels: enhancement

#87 some issues fix
  src/Pages/Home/Services/Services.jsx
Labels: enhancement

#88 some issues fix
  src/Pages/Home/Services/Services.jsx
Labels: enhancement

#90 some changes on home page
  .firebase/hosting.YnVpbGQ.cache
  public/service.json
  src/Pages/Contact/Contact.jsx
  src/Pages/Home/About/About.jsx
  src/Pages/Home/Faq/Faq.jsx
  src/Pages/Home/Home/Home.jsx
  src/Pages/Home/Services/Services.jsx
Labels: enhancement

#89 handle some error and use toast to show them
  src/Pages/Home/Login/Login.jsx
  src/Pages/Home/Register/Register.js
  src/Pages/MobileAuth/MobileAuth.jsx
  src/Shared/Navbar/Navbar.jsx
Labels: enhancement

#91 Ra/login page#2
  src/Pages/Home/Register/Register.js
  src/Shared/Navbar/Navbar.jsx
Labels: bug, enhancement

#92 deployment updated
  .firebase/hosting.YnVpbGQ.cache
  src/App.js
  src/index.js
Labels: enhancement, deployment updated

#93 redesigned the services
  .firebase/hosting.YnVpbGQ.cache
  src/Pages/Home/Services/Services.css
  src/Pages/Home/Services/Services.jsx
  src/index.js
Labels: enhancement, deployment updated

#94 error handle
  src/Pages/Home/Register/Register.js
Labels: enhancement

#95 deployment updated
  .firebase/hosting.YnVpbGQ.cache
  src/App.js
  src/index.js
Labels: deployment updated

#96 service section redesigned and stylish hover effect added
  .firebase/hosting.YnVpbGQ.cache
  src/Pages/Home/Services/Services.css
  src/Pages/Home/Services/Services.jsx
Labels: enhancement, deployment updated

#97 some bug fix
  .firebase/hosting.YnVpbGQ.cache
  src/Pages/Home/Services/Services.css
  src/Pages/Home/Services/Services.jsx
Labels: bug, enhancement, deployment updated

#99 little bug fix
  .firebase/hosting.YnVpbGQ.cache
  src/Pages/Home/Banner/Banner.jsx
  src/Pages/Home/Services/Services.css
  src/Pages/Home/Services/Services.jsx
Labels: bug, enhancement, deployment updated

#100 service card in component
  src/Components/ServiceCard/ServiceCard.jsx
  src/Pages/Home/Services/Services.jsx
Labels: enhancement

#101 navbar routes are fix
  .firebase/hosting.YnVpbGQ.cache
  src/Shared/Navbar/Navbar.jsx
Labels: enhancement

#103 some bug fix
  public/service.json
  src/Pages/Home/Services/Services.jsx
  src/Shared/Navbar/Navbar.jsx
Labels: bug, enhancement, deployment updated

#104 contact form added
  .firebase/hosting.YnVpbGQ.cache
Labels: enhancement

#106 messenger chat implemented
  .firebase/hosting.YnVpbGQ.cache
  package-lock.json
  package.json
  src/App.js
  src/Pages/Contact/Contact.jsx
Labels: enhancement, deployment updated

#108 fix the problem in faq section
  package-lock.json
  src/Pages/Home/Faq/Faq.jsx
Labels: bug

#109 Faq content added
  src/Pages/Home/Faq/Faq.jsx
Labels: enhancement
